media:
  label: Website Media
  input: public/media
  output: /media

content:
  - name: posts
    label: Blog Posts
    type: collection
    path: src/content/posts
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: date
        label: Publication Date
        type: date
        required: true
      - name: author
        label: Author
        type: string
        required: true
        description: "Author username."
      - name: excerpt
        label: Excerpt
        type: text
        description: "A short summary of the post, used for previews (optional)."
      - name: image
        label: Image
        type: image
        description: "Post image."
      - name: body
        label: Main Content
        type: rich-text
        description: "The full content of the blog post."
    view:
      primary: title
      fields: [title, date, author]
      sort: [date, title]
      default:
        sort: date
        order: desc

  # --- Add other content types here ---
  # Example for a single "About Us" page:
  # - name: about_page
  #   label: About Us Page
  #   type: file
  #   path: src/content/pages/about.md # Path to the single file
  #   format: yaml-frontmatter
  #   fields:
  #     - name: title
  #       label: Page Title
  #       type: string
  #     - name: hero_image
  #       label: Hero Image
  #       type: image
  #     - name: mission_statement
  #       label: Mission Statement
  #       type: text
  #     - name: body
  #       label: Page Content
  #       type: rich-text
