# Media Settings
media:
  label: Website Media
  input: public/media
  output: /media

content:
  # Blog Posts
  - name: posts
    label: Blog Posts
    type: collection
    path: src/content/posts
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: date
        label: Publication Date
        type: date
        required: true
      - name: author
        label: Author
        type: reference
        required: true
        options:
          collection: authors
        description: "Select the author of the post."
      - name: tags
        label: Tags
        type: reference
        list: true
        options:
          collection: tags
          value: "{name}"
          multiple: true
        required: false
        description: "Select tags for the post."
      - name: excerpt
        label: Excerpt
        type: text
        description: "A short summary of the post, used for previews (optional)."
      - name: image
        label: Image
        type: image
        options:
          extensions: [jpg, jpeg, png, gif, svg, webp]
        description: "Post image."
      - name: imageAlt
        label: Image Alt
        type: string
        description: "Image alt text. (required if image is set)"
      - name: body
        label: Main Content
        type: rich-text
        description: "The full content of the blog post."
    view:
      primary: title
      fields: [title, date, "author.displayName"]
      sort: [date, title]
      default:
        sort: date
        order: desc

  # Tags
  - name: tags
    label: Tags
    type: collection
    path: src/content/tags
    format: json
    filename: "{fields.id}.json"
    fields:
      - name: name
        label: Name
        type: string
        required: true
      - name: description
        label: Description
        type: string
        required: false
        description: "Description, not displayed anywhere."
      - name: id
        label: Id
        type: uuid
        options:
          editable: false
    view:
      primary: name
      fields: [name, description]
      sort: [name]
      default:
        sort: name
        order: asc

  # Authors
  - name: authors
    label: Authors
    type: collection
    path: src/content/authors
    format: json
    filename: "{fields.id}.json"
    fields:
      - name: username
        label: Username
        type: string
        required: true
        description: "Your school username."
      - name: displayName
        label: Display Name
        type: string
        required: true
        description: "Publicly visible name."
      - name: role
        label: Role
        type: string
        required: true
        description: "Your role in the team."
      - name: id
        label: Id
        type: uuid
        options:
          editable: false

    view:
      primary: username
      fields: [username, displayName, role]
      sort: [username, displayName]
      default:
        sort: username
        order: asc

  # --- Add other content types here ---
  # Example for a single "About Us" page:
  # - name: about_page
  #   label: About Us Page
  #   type: file
  #   path: src/content/pages/about.md # Path to the single file
  #   format: yaml-frontmatter
  #   fields:
  #     - name: title
  #       label: Page Title
  #       type: string
  #     - name: hero_image
  #       label: Hero Image
  #       type: image
  #     - name: mission_statement
  #       label: Mission Statement
  #       type: text
  #     - name: body
  #       label: Page Content
  #       type: rich-text
