# Media Settings
media:
  label: Website Media
  input: public/media
  output: /media

content:
  # Blog Posts
  - name: posts
    label: Blog Posts
    type: collection
    path: src/content/posts
    filename: "{fields.title}.md"
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: status
        label: Current Status
        type: select
        required: true
        options:
          values: [Draft, Published, Archived]
      - name: date
        label: Publication Date
        type: date
        required: true
      - name: author
        label: Author
        type: reference
        required: true
        options:
          collection: authors
          label: "{displayName}"
          value: "{username}"
        description: "Select the author of the post."
      - name: tags
        label: Tags
        type: reference
        options:
          collection: tags
          label: "{tagName}"
          value: "{tagName}"
          multiple: true
        required: false
        description: "Select tags for the post."
      - name: excerpt
        label: Excerpt
        type: string
        required: true
        options:
          maxlength: 120
        description: "A short summary of the post, used for previews."
      - name: image
        label: Image
        type: image
        options:
          extensions: [jpg, jpeg, png, gif, svg, webp]
        description: "Post image."
      - name: imageAlt
        label: Image Alt
        type: string
        description: "What is visible on the image? (Required if image is set)"
      - name: body
        label: Main Content
        type: rich-text
        description: "The full content of the blog post."
    view:
      primary: title
      fields: [title, date, author, tags]
      sort: [date, title]
      default:
        sort: date
        order: desc

  # Tags
  - name: tags
    label: Tags
    type: collection
    path: src/content/tags
    format: json
    filename: "{fields.tagName}.json"
    fields:
      - name: tagName
        label: Name
        type: string
        required: true
      - name: description
        label: Description
        type: string
        required: false
        description: "Description, not displayed anywhere."
    view:
      primary: tagName
      fields: [tagName, description]
      sort: [tagName]
      default:
        sort: tagName
        order: asc

  # Authors
  - name: authors
    label: Authors
    type: collection
    path: src/content/authors
    format: json
    filename: "{fields.id}.json"
    fields:
      - name: username
        label: Username
        type: string
        required: true
        description: "Your school username."
      - name: displayName
        label: Display Name
        type: string
        required: true
        description: "Publicly visible name."
      - name: role
        label: Role
        type: string
        required: true
        description: "Your role in the team."

    view:
      primary: username
      fields: [username, displayName, role]
      sort: [username, displayName]
      default:
        sort: username
        order: asc

  # Sponsors
  - name: sponsors
    label: Sponsors
    type: collection
    path: src/content/sponsors
    format: json
    filename: "{fields.name}.json"
    fields:
      - name: name
        label: Sponsor Name
        type: string
        required: true
        description: "The official name of the sponsor."
      - name: image
        label: Sponsor Logo
        type: image
        required: true
        options:
          extensions: [jpg, jpeg, png, gif, svg, webp]
        description: "The sponsor's logo."
      - name: website
        label: Website URL
        type: string
        required: false
        description: "The URL of the sponsor's website."
    view:
      primary: name
      fields: [name]
      sort: [name]
      default:
        sort: name
        order: asc

  # Robots
  - name: robots
    label: Robots
    type: collection
    path: src/content/robots
    format: json
    filename: "{fields.id}.json"
    fields:
      - name: id
        label: Robot ID
        type: string
        required: true
        description: "{robot name}-{year} (captainstan-2025)"
      - name: name
        label: Robot Name
        type: string
        required: true
        description: "The official name of the robot."
      - name: year
        label: Year
        type: string
        required: true
        description: "The year the robot was built."
      - name: game
        label: Game
        type: string
        required: true
        description: "The game the robot was built for."
      - name: description
        label: Description
        type: string
        required: true
        description: "A short description of the robot."
      - name: features
        label: Features
        type: select
        required: true
        description: "A list of features of the robot."
        options:
          creatable: true
          multiple: true
      - name: imageUrl
        label: Robot Image
        type: image
        required: true
        options:
          extensions: [jpg, jpeg, png, gif, svg, webp]
        description: "The image of the robot."
      - name: imageAlt
        label: Image Alt
        type: string
        description: "The alt text for the image."
    view:
      primary: name
      fields: [name]
      sort: [name]
      default:
        sort: name
        order: asc

  # Whitelisted Emails
  - name: whitelisted_emails
    label: Whitelisted Emails
    type: file
    path: src/content/whitelisted-user-emails.json
    fields:
      - name: emails
        label: Allowed Users
        type: select
        required: true
        description: "A list of the emails of the allowed users."
        options:
          creatable: true
          multiple: true